import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

i18n.use(initReactI18next).init({
  resources: {
    en: {
      translation: {
        diagnostics: 'Health Diagnostics',
        cancer_detection: 'Cancer Detection',
        chest_xray: 'Chest X-ray',
        disease_prediction: 'Disease Prediction',
        nearby_hospitals: 'Nearby Hospitals',
        upload_skin_image: 'Upload Skin Image',
        upload_xray: 'Upload Chest X-ray',
        predict_disease: 'Predict Disease',
        use_location: 'Use My Location',
        find_hospitals: 'Find Hospitals',
        select_image: 'Please select an image.',
        select_symptoms: 'Please select at least one symptom.',
        select_symptoms_placeholder: 'Select up to 3 symptoms',
        provide_location: 'Please provide location coordinates.',
        server_error: 'Failed to connect to server. Is the backend running?',
        location_denied: 'Location access denied. Enter coordinates manually.',
        fever: 'Fever',
        headache: 'Headache',
        cough: 'Cough',
        diarrhea: 'Diarrhea',
        vomiting: 'Vomiting',
        shortness_of_breath: 'Shortness of Breath',
        pain_chest: 'Chest Pain',
        fatigue: 'Fatigue',
        chills: 'Chills',
        sore_to_touch: 'Sore to Touch',
        result: 'Result',
        confidence: 'Confidence',
        disclaimer: 'Disclaimer: This is not a professional diagnosis. Consult a doctor.',
        discuss_prompt: 'Want to discuss this? Use the chat or journal to share your feelings.',
        unknown: 'Unknown',
        address: 'Address',
        phone: 'Phone',
        distance: 'Distance',
        no_address: 'No address',
        no_phone: 'No phone',
        na: 'N/A',
        welcome: 'Welcome to HealthBot',
        mental_health_chat: 'Mental Health Chat',
        chat_placeholder: 'Share your thoughts or feelings...',
        translate: 'Translate',
        translated: 'Translated',
        translation_error: 'Translation failed',
        spanish: 'Spanish',
        french: 'French',
        german: 'German',
        send: 'Send',app_title: 'Virtual AI Therapist',
    initial_ai_message: 'Hi! I’m your virtual therapist—how can I support you today?',
    message_limit_reached: 'You’ve reached the 10-message daily limit. Upgrade to premium for unlimited access!',
    chat_error: 'Sorry, I couldn’t process your request. Please try again.',
    journal_error: 'Failed to save journal entry.',
    logout_error: 'Logout failed',
    subscription_plans: 'Subscription Plans',
    free_plan: 'Free',
    free_plan_features: '10 messages/day\nBasic features',
    premium_plan: 'Premium',
    premium_plan_features: 'Unlimited messages\nAdvanced features',
    current_plan: 'Current Plan',
    upgrade_button: 'Upgrade - $5/month',
    premium_upgrade_soon: 'Premium upgrade coming soon!',
    close: 'Close',
    premium: 'Premium',
    upgrade_premium: 'Upgrade to Premium',
    profile: 'Profile',
    settings: 'Settings',
    history: 'History',
    journal: 'Journal',
    close_journal: 'Close Journal',
    open_journal: 'Open Journal',
    messages_today: 'Messages today: {{count}}/10 {{premium}}',
    chat_disclaimer: 'Disclaimer: This is not a substitute for professional therapy. Contact a licensed therapist for support.',
    light_mode: 'Light Mode',
    dark_mode: 'Dark Mode'
      }
    },
    hi: {
      translation: {
        diagnostics: 'स्वास्थ्य निदान',
        cancer_detection: 'कैंसर जांच',
        chest_xray: 'छाती का एक्स-रे',
        disease_prediction: 'रोग भविष्यवाणी',
        nearby_hospitals: 'नजदीकी अस्पताल',
        upload_skin_image: 'त्वचा की छवि अपलोड करें',
        upload_xray: 'छाती का एक्स-रे अपलोड करें',
        predict_disease: 'रोग की भविष्यवाणी करें',
        use_location: 'मेरे स्थान का उपयोग करें',
        find_hospitals: 'अस्पताल खोजें',
        select_image: 'कृपया एक छवि चुनें।',
        select_symptoms: 'कृपया कम से कम एक लक्षण चुनें।',
        select_symptoms_placeholder: '3 लक्षणों तक चुनें',
        provide_location: 'कृपया स्थान निर्देशांक प्रदान करें।',
        server_error: 'सर्वर से कनेक्ट करने में विफल। क्या बैकएंड चल रहा है?',
        location_denied: 'स्थान पहुंच अस्वीकृत। मैन्युअल रूप से निर्देशांक दर्ज करें।',
        fever: 'बुखार',
        headache: 'सिरदर्द',
        cough: 'खांसी',
        diarrhea: 'दस्त',
        vomiting: 'उल्टी',
        shortness_of_breath: 'सांस की तकलीफ',
        pain_chest: 'सीने में दर्द',
        fatigue: 'थकान',
        chills: 'ठंड लगना',
        sore_to_touch: 'छूने में दर्द',
        result: 'परिणाम',
        confidence: 'विश्वास',
        disclaimer: 'अस्वीकरण: यह पेशेवर निदान नहीं है। डॉक्टर से परामर्श करें।',
        discuss_prompt: 'इस पर चर्चा करना चाहते हैं? चैट या जर्नल का उपयोग करें।',
        unknown: 'अज्ञात',
        address: 'पता',
        phone: 'फोन',
        distance: 'दूरी',
        no_address: 'कोई पता नहीं',
        no_phone: 'कोई फोन नहीं',
        na: 'लागू नहीं',
        welcome: 'हेल्थबॉट में आपका स्वागत है',
        mental_health_chat: 'मानसिक स्वास्थ्य चैट',
        chat_placeholder: 'अपने विचार या भावनाएँ साझा करें...',
        translate: 'अनुवाद करें',
        translated: 'अनुवादित',
        translation_error: 'अनुवाद विफल',
        spanish: 'स्पेनिश',
        french: 'फ्रेंच',
        german: 'जर्मन',
        send: 'भेजें',
        app_title: 'वर्चुअल एआई थेरेपिस्ट',
    initial_ai_message: 'हाय! मैं आपका वर्चुअल थेरेपिस्ट हूँ—मैं आपकी कैसे मदद कर सकता हूँ?',
    message_limit_reached: 'आपने 10-संदेश दैनिक सीमा तक पहुंच गए हैं। असीमित उपयोग के लिए प्रीमियम में अपग्रेड करें!',
    chat_error: 'क्षमा करें, मैं आपका अनुरोध संसाधित नहीं कर सका। कृपया पुनः प्रयास करें।',
    journal_error: 'जर्नल प्रविष्टि सहेजने में विफल।',
    logout_error: 'लॉगआउट विफल',
    subscription_plans: 'सदस्यता योजनाएँ',
    free_plan: 'मुफ्त',
    free_plan_features: '10 संदेश/दिन\nमूलभूत सुविधाएँ',
    premium_plan: 'प्रीमियम',
    premium_plan_features: 'असीमित संदेश\nउन्नत सुविधाएँ',
    current_plan: 'वर्तमान योजना',
    upgrade_button: 'अपग्रेड करें - $5/माह',
    premium_upgrade_soon: 'प्रीमियम अपग्रेड जल्द ही आ रहा है!',
    close: 'बंद करें',
    premium: 'प्रीमियम',
    upgrade_premium: 'प्रीमियम में अपग्रेड करें',
    profile: 'प्रोफाइल',
    settings: 'सेटिंग्स',
    history: 'इतिहास',
    journal: 'जर्नल',
    close_journal: 'जर्नल बंद करें',
    open_journal: 'जर्नल खोलें',
    messages_today: 'आज के संदेश: {{count}}/10 {{premium}}',
    chat_disclaimer: 'अस्वीकरण: यह पेशेवर थेरेपी का विकल्प नहीं है। समर्थन के लिए लाइसेंस प्राप्त थेरेपिस्ट से संपर्क करें।',
    light_mode: 'लाइट मोड',
    dark_mode: 'डार्क मोड'
      }
    },
    es: {
      translation: {
        diagnostics: 'Diagnósticos de Salud',
        cancer_detection: 'Detección de Cáncer',
        chest_xray: 'Radiografía de Tórax',
        disease_prediction: 'Predicción de Enfermedades',
        nearby_hospitals: 'Hospitales Cercanos',
        upload_skin_image: 'Subir Imagen de Piel',
        upload_xray: 'Subir Radiografía de Tórax',
        predict_disease: 'Predecir Enfermedad',
        use_location: 'Usar Mi Ubicación',
        find_hospitals: 'Encontrar Hospitales',
        select_image: 'Por favor, selecciona una imagen.',
        select_symptoms: 'Por favor, selecciona al menos un síntoma.',
        select_symptoms_placeholder: 'Selecciona hasta 3 síntomas',
        provide_location: 'Por favor, proporciona coordenadas de ubicación.',
        server_error: 'No se pudo conectar al servidor. ¿Está el backend ejecutándose?',
        location_denied: 'Acceso a ubicación denegado. Ingresa coordenadas manualmente.',
        fever: 'Fiebre',
        headache: 'Dolor de cabeza',
        cough: 'Tos',
        diarrhea: 'Diarrea',
        vomiting: 'Vómitos',
        shortness_of_breath: 'Dificultad para respirar',
        pain_chest: 'Dolor torácico',
        fatigue: 'Fatiga',
        chills: 'Escalofríos',
        sore_to_touch: 'Dolor al tocar',
        result: 'Resultado',
        confidence: 'Confianza',
        disclaimer: 'Descargo de responsabilidad: Esto no es un diagnóstico profesional. Consulta a un médico.',
        discuss_prompt: '¿Quieres hablar de esto? Usa el chat o diario para compartir tus sentimientos.',
        unknown: 'Desconocido',
        address: 'Dirección',
        phone: 'Teléfono',
        distance: 'Distancia',
        no_address: 'Sin dirección',
        no_phone: 'Sin teléfono',
        na: 'N/A',
        welcome: 'Bienvenido a HealthBot',
        mental_health_chat: 'Chat de Salud Mental',
        chat_placeholder: 'Comparte tus pensamientos o sentimientos...',
        translate: 'Traducir',
        translated: 'Traducido',
        translation_error: 'Fallo en la traducción',
        spanish: 'Español',
        french: 'Francés',
        german: 'Alemán',
        send: 'Enviar',
        app_title: 'Terapeuta Virtual de IA',
    initial_ai_message: '¡Hola! Soy tu terapeuta virtual, ¿cómo puedo ayudarte hoy?',
    message_limit_reached: 'Has alcanzado el límite diario de 10 mensajes. ¡Actualiza a premium para acceso ilimitado!',
    chat_error: 'Lo siento, no pude procesar tu solicitud. Por favor, intenta de nuevo.',
    journal_error: 'No se pudo guardar la entrada del diario.',
    logout_error: 'Fallo al cerrar sesión',
    subscription_plans: 'Planes de Suscripción',
    free_plan: 'Gratis',
    free_plan_features: '10 mensajes/día\nFunciones básicas',
    premium_plan: 'Premium',
    premium_plan_features: 'Mensajes ilimitados\nFunciones avanzadas',
    current_plan: 'Plan Actual',
    upgrade_button: 'Actualizar - $5/mes',
    premium_upgrade_soon: '¡Actualización premium pronto!',
    close: 'Cerrar',
    premium: 'Premium',
    upgrade_premium: 'Actualizar a Premium',
    profile: 'Perfil',
    settings: 'Configuraciones',
    history: 'Historial',
    journal: 'Diario',
    close_journal: 'Cerrar Diario',
    open_journal: 'Abrir Diario',
    messages_today: 'Mensajes hoy: {{count}}/10 {{premium}}',
    chat_disclaimer: 'Descargo de responsabilidad: Esto no sustituye a la terapia profesional. Contacta a un terapeuta licenciado para apoyo.',
    light_mode: 'Modo Claro',
    dark_mode: 'Modo Oscuro'
      }
    },
    fr: {
      translation: {
        diagnostics: 'Diagnostics de Santé',
        cancer_detection: 'Détection du Cancer',
        chest_xray: 'Radiographie Thoracique',
        disease_prediction: 'Prédiction de Maladies',
        nearby_hospitals: 'Hôpitaux à Proximité',
        upload_skin_image: 'Télécharger une Image de Peau',
        upload_xray: 'Télécharger une Radiographie Thoracique',
        predict_disease: 'Prédire une Maladie',
        use_location: 'Utiliser Ma Position',
        find_hospitals: 'Trouver des Hôpitaux',
        select_image: 'Veuillez sélectionner une image.',
        select_symptoms: 'Veuillez sélectionner au moins un symptôme.',
        select_symptoms_placeholder: 'Sélectionnez jusqu\'à 3 symptômes',
        provide_location: 'Veuillez fournir les coordonnées de localisation.',
        server_error: 'Échec de la connexion au serveur. Le backend est-il en cours d\'exécution ?',
        location_denied: 'Accès à la localisation refusé. Entrez les coordonnées manuellement.',
        fever: 'Fièvre',
        headache: 'Maux de tête',
        cough: 'Toux',
        diarrhea: 'Diarrhée',
        vomiting: 'Vomissements',
        shortness_of_breath: 'Essoufflement',
        pain_chest: 'Douleur thoracique',
        fatigue: 'Fatigue',
        chills: 'Frissons',
        sore_to_touch: 'Douloureux au toucher',
        result: 'Résultat',
        confidence: 'Confiance',
        disclaimer: 'Avertissement : Ceci n\'est pas un diagnostic professionnel. Consultez un médecin.',
        discuss_prompt: 'Voulez-vous en discuter ? Utilisez le chat ou le journal pour partager vos sentiments.',
        unknown: 'Inconnu',
        address: 'Adresse',
        phone: 'Téléphone',
        distance: 'Distance',
        no_address: 'Aucune adresse',
        no_phone: 'Aucun téléphone',
        na: 'N/A',
        welcome: 'Bienvenue sur HealthBot',
        mental_health_chat: 'Chat de Santé Mentale',
        chat_placeholder: 'Partagez vos pensées ou sentiments...',
        translate: 'Traduire',
        translated: 'Traduit',
        translation_error: 'Échec de la traduction',
        spanish: 'Espagnol',
        french: 'Français',
        german: 'Allemand',
        send: 'Envoyer', app_title: 'Virtueller KI-Therapeut',
    initial_ai_message: 'Hallo! Ich bin dein virtueller Therapeut – wie kann ich dir heute helfen?',
    message_limit_reached: 'Du hast das tägliche Limit von 10 Nachrichten erreicht. Upgrade auf Premium für unbegrenzten Zugriff!',
    chat_error: 'Entschuldigung, ich konnte deine Anfrage nicht verarbeiten. Bitte versuche es erneut.',
    journal_error: 'Fehler beim Speichern des Tagebucheintrags.',
    logout_error: 'Abmeldung fehlgeschlagen',
    subscription_plans: 'Abonnementpläne',
    free_plan: 'Kostenlos',
    free_plan_features: '10 Nachrichten/Tag\nGrundlegende Funktionen',
    premium_plan: 'Premium',
    premium_plan_features: 'Unbegrenzte Nachrichten\nErweiterte Funktionen',
    current_plan: 'Aktueller Plan',
    upgrade_button: 'Upgrade - 5 $/Monat',
    premium_upgrade_soon: 'Premium-Upgrade bald verfügbar!',
    close: 'Schließen',
    premium: 'Premium',
    upgrade_premium: 'Auf Premium upgraden',
    profile: 'Profil',
    settings: 'Einstellungen',
    history: 'Verlauf',
    journal: 'Tagebuch',
    close_journal: 'Tagebuch schließen',
    open_journal: 'Tagebuch öffnen',
    messages_today: 'Nachrichten heute: {{count}}/10 {{premium}}',
    chat_disclaimer: 'Haftungsausschluss: Dies ist kein Ersatz für professionelle Therapie. Kontaktiere einen lizenzierten Therapeuten für Unterstützung.',
    light_mode: 'Heller Modus',
    dark_mode: 'Dunkler Modus'
      }
    },
    de: {
      translation: {
        diagnostics: 'Gesundheitsdiagnostik',
        cancer_detection: 'Krebsdiagnose',
        chest_xray: 'Röntgenaufnahme des Brustkorbs',
        disease_prediction: 'Krankheitsvorhersage',
        nearby_hospitals: 'Nahegelegene Krankenhäuser',
        upload_skin_image: 'Hautbild hochladen',
        upload_xray: 'Röntgenaufnahme des Brustkorbs hochladen',
        predict_disease: 'Krankheit vorhersagen',
        use_location: 'Meinen Standort verwenden',
        find_hospitals: 'Krankenhäuser finden',
        select_image: 'Bitte wählen Sie ein Bild aus.',
        select_symptoms: 'Bitte wählen Sie mindestens ein Symptom aus.',
        select_symptoms_placeholder: 'Bis zu 3 Symptome auswählen',
        provide_location: 'Bitte geben Sie Standortkoordinaten an.',
        server_error: 'Verbindung zum Server fehlgeschlagen. Läuft der Backend?',
        location_denied: 'Standortzugriff verweigert. Koordinaten manuell eingeben.',
        fever: 'Fieber',
        headache: 'Kopfschmerzen',
        cough: 'Husten',
        diarrhea: 'Durchfall',
        vomiting: 'Erbrechen',
        shortness_of_breath: 'Kurzatmigkeit',
        pain_chest: 'Brustschmerzen',
        fatigue: 'Müdigkeit',
        chills: 'Schüttelfrost',
        sore_to_touch: 'Schmerzhaft bei Berührung',
        result: 'Ergebnis',
        confidence: 'Zuversicht',
        disclaimer: 'Haftungsausschluss: Dies ist keine professionelle Diagnose. Konsultieren Sie einen Arzt.',
        discuss_prompt: 'Möchten Sie darüber sprechen? Nutzen Sie den Chat oder das Tagebuch, um Ihre Gefühle zu teilen.',
        unknown: 'Unbekannt',
        address: 'Adresse',
        phone: 'Telefon',
        distance: 'Entfernung',
        no_address: 'Keine Adresse',
        no_phone: 'Kein Telefon',
        na: 'N/A',
        welcome: 'Willkommen bei HealthBot',
        mental_health_chat: 'Chat für psychische Gesundheit',
        chat_placeholder: 'Teilen Sie Ihre Gedanken oder Gefühle...',
        translate: 'Übersetzen',
        translated: 'Übersetzt',
        translation_error: 'Übersetzung fehlgeschlagen',
        spanish: 'Spanisch',
        french: 'Französisch',
        german: 'Deutsch',
        send: 'Senden',
        app_title: 'Virtueller KI-Therapeut',
    initial_ai_message: 'Hallo! Ich bin dein virtueller Therapeut – wie kann ich dir heute helfen?',
    message_limit_reached: 'Du hast das tägliche Limit von 10 Nachrichten erreicht. Upgrade auf Premium für unbegrenzten Zugriff!',
    chat_error: 'Entschuldigung, ich konnte deine Anfrage nicht verarbeiten. Bitte versuche es erneut.',
    journal_error: 'Fehler beim Speichern des Tagebucheintrags.',
    logout_error: 'Abmeldung fehlgeschlagen',
    subscription_plans: 'Abonnementpläne',
    free_plan: 'Kostenlos',
    free_plan_features: '10 Nachrichten/Tag\nGrundlegende Funktionen',
    premium_plan: 'Premium',
    premium_plan_features: 'Unbegrenzte Nachrichten\nErweiterte Funktionen',
    current_plan: 'Aktueller Plan',
    upgrade_button: 'Upgrade - 5 $/Monat',
    premium_upgrade_soon: 'Premium-Upgrade bald verfügbar!',
    close: 'Schließen',
    premium: 'Premium',
    upgrade_premium: 'Auf Premium upgraden',
    profile: 'Profil',
    settings: 'Einstellungen',
    history: 'Verlauf',
    journal: 'Tagebuch',
    close_journal: 'Tagebuch schließen',
    open_journal: 'Tagebuch öffnen',
    messages_today: 'Nachrichten heute: {{count}}/10 {{premium}}',
    chat_disclaimer: 'Haftungsausschluss: Dies ist kein Ersatz für professionelle Therapie. Kontaktiere einen lizenzierten Therapeuten für Unterstützung.',
    light_mode: 'Heller Modus',
    dark_mode: 'Dunkler Modus'
      }
    }
  },
  lng: 'en',
  fallbackLng: 'en'
});

export default i18n;